//
//  SymbolSearchEngine.swift
//  Iconic
//
//  Tag-based search over Apple's SF Symbols metadata. Matches folder name tokens
//  against the search tags Apple ships in symbol_search.plist (the same data
//  that powers the SF Symbols app search) AND against the symbol name itself —
//  many symbol names like `medal.fill` or `firework` aren't tagged but are
//  trivially matchable by name.
//
//  See `SymbolMetadata.searchTags` (generated by Scripts/extract_symbols.swift).
//

import Foundation

enum SymbolSearchEngine {

    /// Confidence threshold below which we don't return a result — the caller
    /// (SymbolMapper) treats anything below this as "no match" and falls
    /// through to fuzzy matching or the fallback symbol.
    static let minimumConfidence: Double = 0.70

    struct Result {
        let symbol: String
        let confidence: Double
    }

    /// Find the best SF Symbol for a folder name. Returns `nil` if no candidate
    /// meets `minimumConfidence`.
    static func search(folderName: String) -> Result? {
        let tokens = SymbolMapper.publicTokenize(folderName)
        guard !tokens.isEmpty else { return nil }

        // Score every symbol once per token, take the max per symbol.
        var scores: [String: Double] = [:]
        for (index, token) in tokens.enumerated() {
            // First-token boost — the user's primary intent usually lives there.
            let positionMultiplier = index == 0 ? 1.10 : 1.0

            for (symbol, score) in candidateScores(forToken: token) {
                let adjusted = score * positionMultiplier
                if adjusted > (scores[symbol] ?? 0) {
                    scores[symbol] = adjusted
                }
            }
        }

        guard let best = scores.max(by: { $0.value < $1.value }) else { return nil }
        guard best.value >= minimumConfidence else { return nil }

        return Result(symbol: best.key, confidence: min(1.0, best.value))
    }

    // MARK: - Indexes (lazy, built once)

    /// Tag → [symbolName]. Built once from `SymbolMetadata.searchTags`.
    private static let tagIndex: [String: [String]] = {
        var index: [String: [String]] = [:]
        for (symbol, tags) in SymbolMetadata.searchTags {
            for tag in tags {
                index[tag, default: []].append(symbol)
            }
        }
        return index
    }()

    /// Tokenized symbol name → [symbolName]. Lets `unicorn` match a hypothetical
    /// `unicorn.fill` symbol even when Apple's tags don't mention it.
    private static let nameTokenIndex: [String: [String]] = {
        var index: [String: [String]] = [:]
        for symbol in SymbolMetadata.searchTags.keys {
            for piece in symbol.split(separator: ".") {
                let key = String(piece).lowercased()
                index[key, default: []].append(symbol)
            }
        }
        return index
    }()

    private static let allTags: [String] = Array(Set(tagIndex.keys))
    private static let allNameTokens: [String] = Array(Set(nameTokenIndex.keys))

    // MARK: - Scoring

    /// Returns candidate symbols for a single token with raw confidence scores.
    /// Combines exact, substring, and fuzzy matches across both indexes.
    private static func candidateScores(forToken token: String) -> [(String, Double)] {
        var results: [(String, Double)] = []

        // 1. Exact tag hit.
        if let exact = tagIndex[token] {
            results.append(contentsOf: exact.map { ($0, 1.0) })
        }

        // 2. Exact name-component hit. Slightly less authoritative than a tag
        //    (a tag is a curated synonym; a name component is mechanical), but
        //    still extremely high signal.
        if let exact = nameTokenIndex[token] {
            results.append(contentsOf: exact.map { ($0, 0.95) })
        }

        // 3. Substring match on tags. Catches "photograph" → "photo" tag.
        //    Only fire if token is long enough to avoid false positives like
        //    "ai" matching "rain".
        if token.count >= 4 {
            for tag in allTags where tag.count >= 3 {
                if tag.contains(token) || token.contains(tag) {
                    let symbols = tagIndex[tag] ?? []
                    results.append(contentsOf: symbols.map { ($0, 0.80) })
                }
            }
        }

        // 4. Fuzzy match against tags. Last resort for typos / minor variants.
        //    Keep this tighter than substring to avoid noise.
        if token.count >= 5 {
            for tag in allTags where abs(tag.count - token.count) <= 2 {
                let score = SymbolMapper.publicSimilarity(token, tag)
                if score >= 0.80 {
                    let symbols = tagIndex[tag] ?? []
                    results.append(contentsOf: symbols.map { ($0, score * 0.85) })
                }
            }
        }

        // Prefer filled variants when we have a tie — they read better as folder icons.
        return results.map { (symbol, score) in
            let bonus = symbol.hasSuffix(".fill") ? 0.02 : 0.0
            return (symbol, min(1.0, score + bonus))
        }
    }
}
